object Versions {
    const val androidXCoreKtx = "1.12.0"
    const val kotlinBom = "1.8.0"
    const val kotlinCoroutine = "1.7.3"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.7.2"
    const val compose = "1.5.3"
    const val composeBom = "2023.09.00"
    const val composeNavigation = "2.7.3"
    const val composeMaterial3 = "1.1.2"
    const val composeCompiler = "1.5.3"
    const val hilt = "2.48"
    const val hiltNavigationCompose = "1.0.0"
    const val firebaseBom = "32.3.1"
    const val androidDatastore = "1.0.0"
    const val okHttp = "4.11.0"
    const val retrofit = "2.9.0"
    const val retrofitKotlinSerialization = "1.0.0"
    const val kotlinSerialization = "1.6.0"
    const val playServiceAuth = "20.7.0"
    const val googleApiClient = "2.2.0"

    const val jUnit = "4.13.2"
    const val androidXJunitExt = "1.1.5"
    const val espressoCore = "3.5.1"
}